on:
    pull_request:
    push:
      branches:
        - main
  
name: Mooving CI
 
jobs:
  check:
    name: Component Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-component (debug)
        run: cargo install --git https://github.com/bytecodealliance/cargo-component --locked cargo-component      
      - uses: actions-rs/cargo@v1
        with:
          command: component
          args: check

  fmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test-mooving:
    name: Test Mooving
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path mooving/Cargo.toml --all -- --nocapture --manifest-path=mooving/Cargo.toml

  build:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable --no-self-update && rustup default stable && rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
      - name: Install cargo-component (debug)
        run: cargo install --git https://github.com/bytecodealliance/cargo-component --locked cargo-component
      - name: Component check
        run: cargo component build --release
        
        
